import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Searchy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left */}
        {/* x-4 spaces all children with 4 */}
        <div className="flex space-x-4 items-center">
          <p>About</p>
          <p>Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p>Gmail</p>
          <p>Images</p>

          {/* Icon */}

          {/* Avatar */}
        </div>
      </header>
    </div>
  )
}
